
spring:
  batch:
    initialize-schema: always
flare.base:
  data-source:
    jdbc-url: jdbc:h2:mem:FLARE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=Oracle;INIT=CREATE SCHEMA IF NOT EXISTS FLRE_OWNER
    username: FLARE_OWNER
    password: # override in application-env
    maximum-pool-size: 10